--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/27/2022 10:37:58 PM
-- Server version: 8.0.31
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE `misa.web09.ctm.lhdo.ketoan`;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Set default database
--
USE `misa.web09.ctm.lhdo.ketoan`;

--
-- Create table `department`
--
CREATE TABLE department (
  DepartmentID char(36) NOT NULL DEFAULT '' COMMENT 'ID của đơn vị',
  DepartmentCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã đơn vị',
  DepartmentName varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên đơn vị',
  CreatedAt datetime DEFAULT NULL COMMENT 'Thời gian tạo',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo',
  ModifiedAt datetime DEFAULT NULL COMMENT 'Thời gian chỉnh sủa gần nhất',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người chỉnh sửa gần nhất',
  PRIMARY KEY (DepartmentID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Bảng đơn vị';

--
-- Create index `DepartmentCode` on table `department`
--
ALTER TABLE department
ADD UNIQUE INDEX DepartmentCode (DepartmentCode);

--
-- Create index `IDX_department_DepartmentName` on table `department`
--
ALTER TABLE department
ADD INDEX IDX_department_DepartmentName (DepartmentName);

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeID char(36) NOT NULL DEFAULT '' COMMENT 'ID của nhân viên',
  EmployeeCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã nhân viên',
  EmployeeName varchar(100) NOT NULL DEFAULT '' COMMENT 'Tên nhân viên',
  DateOfBirth date DEFAULT NULL COMMENT 'Ngày sinh',
  Gender tinyint DEFAULT NULL COMMENT 'Giới tính ={0: "Nam", 1: "Nữ", 2: "Khác"}',
  IdentityNumber varchar(25) DEFAULT NULL COMMENT 'Số chứng minh nhân dân',
  IdentityIssueDate date DEFAULT NULL COMMENT 'Ngày cấp',
  IdentityIssuePlace varchar(255) DEFAULT NULL COMMENT 'Nơi cấp',
  DepartmentID char(36) NOT NULL DEFAULT '' COMMENT 'ID của Đơn vị',
  JobPositionName varchar(100) DEFAULT NULL COMMENT 'Chức danh',
  Address varchar(255) DEFAULT NULL COMMENT 'Địa chỉ',
  PhoneNumber varchar(50) DEFAULT NULL COMMENT 'Điện thoại di động',
  TelephoneNumber varchar(50) DEFAULT NULL COMMENT 'Điện thoại cố định',
  Email varchar(100) DEFAULT NULL,
  BankAccountNumber varchar(25) DEFAULT NULL COMMENT 'Số tài khoản ngân hàng',
  BankName varchar(255) DEFAULT NULL COMMENT 'Tên ngân hàng',
  BankBranchName varchar(255) DEFAULT NULL COMMENT 'Chi nhánh ngân hàng',
  CreatedAt datetime DEFAULT NULL COMMENT 'Thời gian tạo',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo',
  ModifiedAt datetime DEFAULT NULL COMMENT 'Thời gian chỉnh sủa gần nhất',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người chỉnh sửa gần nhất',
  PRIMARY KEY (EmployeeID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Bảng nhân viên';

--
-- Create index `EmployeeCode` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX EmployeeCode (EmployeeCode);

--
-- Create index `IDX_employee_Email` on table `employee`
--
ALTER TABLE employee
ADD INDEX IDX_employee_Email (Email);

--
-- Create index `IDX_employee_EmployeeName` on table `employee`
--
ALTER TABLE employee
ADD INDEX IDX_employee_EmployeeName (EmployeeName);

--
-- Create index `IDX_employee_IdentityNumber` on table `employee`
--
ALTER TABLE employee
ADD INDEX IDX_employee_IdentityNumber (IdentityNumber);

--
-- Create index `IDX_employee_PhoneNumber` on table `employee`
--
ALTER TABLE employee
ADD INDEX IDX_employee_PhoneNumber (PhoneNumber);

--
-- Create index `IDX_employee_TelephoneNumber` on table `employee`
--
ALTER TABLE employee
ADD INDEX IDX_employee_TelephoneNumber (TelephoneNumber);

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_employee_department_DepartmentID FOREIGN KEY (DepartmentID)
REFERENCES department (DepartmentID);

-- 
-- Dumping data for table department
--
INSERT INTO department VALUES
('d0060e77-560b-11ed-8527-00ffdd253cac', 'DV001', 'Nhân Sự', '2022-10-27 22:27:05', 'Lê Hữu Độ', '2022-10-27 22:27:05', 'Lê Hữu Độ'),
('d0080409-560b-11ed-8527-00ffdd253cac', 'DV002', 'Nhân đào tạo', '2022-10-27 22:27:05', 'Lê Hữu Độ', '2022-10-27 22:27:05', 'Lê Hữu Độ'),
('d00819e0-560b-11ed-8527-00ffdd253cac', 'DV003', 'Nhân Tài chính', '2022-10-27 22:27:05', 'Lê Hữu Độ', '2022-10-27 22:27:05', 'Lê Hữu Độ');

-- 
-- Dumping data for table employee
--
INSERT INTO employee VALUES
('c6d9afba-560c-11ed-8527-00ffdd253cac', 'NV001', 'Lê Hữu Độ', '2022-10-27', 0, '123213921321', '2022-10-27', 'Thanh Hoa', 'd0060e77-560b-11ed-8527-00ffdd253cac', 'Fresher', '', '', '', '', '', '', '', '2022-10-27 22:33:59', 'Lê Hữu Độ', '2022-10-27 22:33:59', 'Lê Hữu Độ'),
('c6da5f11-560c-11ed-8527-00ffdd253cac', 'NV002', 'Lê Thị Hiền', '2022-10-27', 1, '123213921321', '2022-10-27', 'Thanh Hoa', 'd0080409-560b-11ed-8527-00ffdd253cac', 'Fresher', '', '', '', '', '', '', '', '2022-10-27 22:33:59', 'Lê Hữu Độ', '2022-10-27 22:33:59', 'Lê Hữu Độ'),
('c6da6213-560c-11ed-8527-00ffdd253cac', 'NV003', 'Lê Văn Nam', '2022-10-27', 0, '123213921321', '2022-10-27', 'Thanh Hoa', 'd00819e0-560b-11ed-8527-00ffdd253cac', 'Fresher', '', '', '', '', '', '', '', '2022-10-27 22:33:59', 'Lê Hữu Độ', '2022-10-27 22:33:59', 'Lê Hữu Độ');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;